# Coolify configuration for backend
build:
  context: ./backend
  dockerfile: Dockerfile
ports:
  - "8000:8000"
environment:
  - FRONTEND_URL=${FRONTEND_URL}
  - YOUTUBE_CLIENT_ID=${YOUTUBE_CLIENT_ID}
  - YOUTUBE_CLIENT_SECRET=${YOUTUBE_CLIENT_SECRET}
  - YOUTUBE_REFRESH_TOKEN=${YOUTUBE_REFRESH_TOKEN}

